// Code generated by qtc from "dashboard.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/dashboard.qtpl:1
package templates

//line templates/dashboard.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/dashboard.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/dashboard.qtpl:3
type PairingModel struct {
	Player1Name  string
	Player1Score int
	Player2Name  string
	Player2Score int
}

type DashboardPage struct {
	TournamentTitle    string
	TournamentSubtitle string
	RoundCount         int
	Pairings           []PairingModel
}

//line templates/dashboard.qtpl:19
func StreamDashboard(qw422016 *qt422016.Writer, p *DashboardPage) {
//line templates/dashboard.qtpl:19
	qw422016.N().S(`
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  <title>Puchar</title>

  <style>
    .badge-win,
    .badge-defeat {
      color: #FFFFFF;
      border-radius: 3px;
      text-align: center;
      width: 25px;
    }

    .badge-win {
      background: #4BB543;
    }

    .badge-defeat {
      background: #FF0033;
    }
  </style>

</head>


<body>

<div class="container">

<section class="hero">
  <div class="hero-body">
    <p class="title">
    `)
//line templates/dashboard.qtpl:57
	qw422016.E().S(p.TournamentTitle)
//line templates/dashboard.qtpl:57
	qw422016.N().S(`
    </p>
    <p class="subtitle">
    `)
//line templates/dashboard.qtpl:60
	qw422016.E().S(p.TournamentSubtitle)
//line templates/dashboard.qtpl:60
	qw422016.N().S(`
    </p>
  </div>
</section>
<section>
  <div class="columns">
    <div class="column is-three-quarters" style="padding-right: 50px;">
    <nav class="pagination is-small">
      <ul class="pagination-list">
        <li><a class="pagination-link">1</a></li>
      </ul>
    </nav>
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th style="width: 50px;"><abbr title="Board">#</abbr></th>
          <th class="has-text-left">Name</th>
          <th class="has-text-centered">Result</th>
          <th class="has-text-right">Name</th>
        </tr>
      </thead>
      <tbody>
        `)
//line templates/dashboard.qtpl:82
	for _, pairing := range p.Pairings {
//line templates/dashboard.qtpl:82
		qw422016.N().S(`
          <tr>
            <th>?</th>
            <td class="has-text-left">`)
//line templates/dashboard.qtpl:85
		qw422016.E().S(pairing.Player1Name)
//line templates/dashboard.qtpl:85
		qw422016.N().S(`</td>
`)
//line templates/dashboard.qtpl:88
		qw422016.N().S(`
            <td class="is-flex is-justify-content-center">
              `)
//line templates/dashboard.qtpl:90
		if pairing.Player1Score > pairing.Player2Score {
//line templates/dashboard.qtpl:90
			qw422016.N().S(`
                <span class="badge-win mr-1">`)
//line templates/dashboard.qtpl:91
			qw422016.N().D(pairing.Player1Score)
//line templates/dashboard.qtpl:91
			qw422016.N().S(`</span>
                <span class="badge-defeat">`)
//line templates/dashboard.qtpl:92
			qw422016.N().D(pairing.Player2Score)
//line templates/dashboard.qtpl:92
			qw422016.N().S(`</span>
              `)
//line templates/dashboard.qtpl:93
		} else {
//line templates/dashboard.qtpl:93
			qw422016.N().S(`
                <span class="badge-defeat mr-1">`)
//line templates/dashboard.qtpl:94
			qw422016.N().D(pairing.Player1Score)
//line templates/dashboard.qtpl:94
			qw422016.N().S(`</span>
                <span class="badge-win">`)
//line templates/dashboard.qtpl:95
			qw422016.N().D(pairing.Player2Score)
//line templates/dashboard.qtpl:95
			qw422016.N().S(`</span>
              `)
//line templates/dashboard.qtpl:96
		}
//line templates/dashboard.qtpl:96
		qw422016.N().S(`
            </td>
            <td class="has-text-right">`)
//line templates/dashboard.qtpl:98
		qw422016.E().S(pairing.Player2Name)
//line templates/dashboard.qtpl:98
		qw422016.N().S(`</td>
          </tr>
        `)
//line templates/dashboard.qtpl:100
	}
//line templates/dashboard.qtpl:100
	qw422016.N().S(`
      </tbody>
    </table>
    </div>

    <div class="column">
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th style="width: 50px;"><abbr title="Place">#</abbr></th>
            <th>Player</th>
            <th>Points</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</section>

</div>

</body>

</html>
`)
//line templates/dashboard.qtpl:126
}

//line templates/dashboard.qtpl:126
func WriteDashboard(qq422016 qtio422016.Writer, p *DashboardPage) {
//line templates/dashboard.qtpl:126
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/dashboard.qtpl:126
	StreamDashboard(qw422016, p)
//line templates/dashboard.qtpl:126
	qt422016.ReleaseWriter(qw422016)
//line templates/dashboard.qtpl:126
}

//line templates/dashboard.qtpl:126
func Dashboard(p *DashboardPage) string {
//line templates/dashboard.qtpl:126
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/dashboard.qtpl:126
	WriteDashboard(qb422016, p)
//line templates/dashboard.qtpl:126
	qs422016 := string(qb422016.B)
//line templates/dashboard.qtpl:126
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/dashboard.qtpl:126
	return qs422016
//line templates/dashboard.qtpl:126
}
